# typed: false
# frozen_string_literal: true

# GENERATED by scripts/update-rassumfrassum.py from GitHub releases -- do not edit.
# The update-rassumfrassum workflow regenerates this file on new releases.
# Edit the script or template, never this file.
class Rassumfrassum < Formula
  include Language::Python::Virtualenv

  desc "LSP/JSONRPC multiplexer connecting one LSP client to multiple servers"
  homepage "https://github.com/joaotavora/rassumfrassum"
  url "https://github.com/joaotavora/rassumfrassum/archive/refs/tags/v0.3.5.tar.gz"
  sha256 "5cd3215d59a1d13bf2a7ae65ad94387b70160365bae206cc0d03c3abeb060a5f"
  license "GPL-3.0-or-later"

  depends_on "python@3.13"

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rass --version")
  end
end
