# typed: false
# frozen_string_literal: true

# GENERATED by scripts/update-tileserver-gl.py from the npm registry -- do not edit.
# tileserver-gl ships only via npm and pulls native modules at install time. Its
# renderer (@maplibre/maplibre-gl-native) downloads an ABI-specific prebuilt binary
# with no source fallback, so this formula pins a Node whose ABI maplibre actually
# publishes a macOS prebuild for (node@22 here). The update-tileserver-gl
# workflow regenerates this file -- re-picking the Node line -- on new releases.
# Edit the script or template, never this file.
class TileserverGl < Formula
  desc "Map tile server for vector and raster tiles with server-side GL rendering"
  homepage "https://github.com/maptiler/tileserver-gl"
  url "https://registry.npmjs.org/tileserver-gl/-/tileserver-gl-5.6.0.tgz"
  sha256 "9340bcb4e59e5f3908685721396d4a0c3c431d19e10c1bec65009133035d48f0"
  license "BSD-2-Clause"

  depends_on :macos
  depends_on "node@22"

  def install
    node = Formula["node@22"]
    ENV.prepend_path "PATH", node.opt_bin

    # sharp builds from source when it detects a globally-installed libvips (e.g.
    # from `brew install vips`), which would need a toolchain this formula does
    # not pull in. Force its self-contained prebuilt binaries instead.
    ENV["SHARP_IGNORE_GLOBAL_LIBVIPS"] = "1"

    # Install runtime deps in-tree. maplibre-gl-native and canvas resolve prebuilt,
    # self-contained binaries (their dylibs are bundled beside the .node files), so
    # no Homebrew cairo/pango/vips dependencies are needed. Don't build from source
    # -- maplibre publishes no source fallback for these ABIs anyway.
    system node.opt_bin/"npm", "install", "--omit=dev", "--no-audit", "--no-fund"

    libexec.install Dir["*"]

    # main.js' shebang is `#!/usr/bin/env node`; if another Node (e.g. Homebrew's
    # current `node`) comes first on PATH, the prebuilt native ABI mismatches and
    # crashes. Pin the interpreter to the Node this was built against.
    (bin/"tileserver-gl").write <<~SH
      #!/bin/bash
      exec "#{node.opt_bin}/node" "#{libexec}/src/main.js" "$@"
    SH
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tileserver-gl --version")
  end
end
