# typed: false
# frozen_string_literal: true

# GENERATED by scripts/update-zig-master.py from https://ziglang.org/download/index.json -- do not edit.
# Zig's master channel is a moving target (only the latest nightly is kept
# online), so the `update-zig-master` workflow regenerates this file whenever a
# new build is published. Edit the script or template, never this file.
class ZigMaster < Formula
  desc "Programming language designed for robustness, optimality, and clarity"
  homepage "https://ziglang.org"
  version "0.17.0-dev.1824+7988f7952"
  license "MIT"

  on_macos do
    on_arm do
      url "https://ziglang.org/builds/zig-aarch64-macos-0.17.0-dev.1824+7988f7952.tar.xz"
      sha256 "6b0538fd45e58adae3ef02e500d8c58774ed28578658c1234e89f468a1a4ec76"
    end
    on_intel do
      url "https://ziglang.org/builds/zig-x86_64-macos-0.17.0-dev.1824+7988f7952.tar.xz"
      sha256 "46db34a5b1101a58a42d5852e6746cb199b6ea64db388f5488a814d1210cb323"
    end
  end

  on_linux do
    on_arm do
      url "https://ziglang.org/builds/zig-aarch64-linux-0.17.0-dev.1824+7988f7952.tar.xz"
      sha256 "8386c913545222c479300e031e0c1e6220751922d283e646b344c7670932a31e"
    end
    on_intel do
      url "https://ziglang.org/builds/zig-x86_64-linux-0.17.0-dev.1824+7988f7952.tar.xz"
      sha256 "b2c228dea21ecc4d0b56f78685b7f296fd095e56b630dec3960a476c0512b631"
    end
  end

  def install
    # The archive unpacks to `zig`, `lib/`, `doc/`, and LICENSE. Keep them
    # together in libexec and expose only the compiler on PATH; Zig finds its
    # std library relative to the resolved binary, so the symlink works.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"zig"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zig version")
  end
end
