# typed: false
# frozen_string_literal: true

# GENERATED by scripts/update-zig-master.py from https://ziglang.org/download/index.json -- do not edit.
# Zig's master channel is a moving target (only the latest nightly is kept
# online), so the `update-zig-master` workflow regenerates this file whenever a
# new build is published. Edit the script or template, never this file.
class ZigMaster < Formula
  desc "Programming language designed for robustness, optimality, and clarity"
  homepage "https://ziglang.org"
  version "0.17.0-dev.2320+1e770dbef"
  license "MIT"

  on_macos do
    on_arm do
      url "https://ziglang.org/builds/zig-aarch64-macos-0.17.0-dev.2320+1e770dbef.tar.xz"
      sha256 "30137724168da4577508609cc3cd648db3ca3a841cc034e6e3c2b34b82be7079"
    end
    on_intel do
      url "https://ziglang.org/builds/zig-x86_64-macos-0.17.0-dev.2320+1e770dbef.tar.xz"
      sha256 "f965d20b7118151a73da37a251d24dd696d1f025aa702110e8c1433eb1d4bf36"
    end
  end

  on_linux do
    on_arm do
      url "https://ziglang.org/builds/zig-aarch64-linux-0.17.0-dev.2320+1e770dbef.tar.xz"
      sha256 "7c249e4e2e5460b69b1125ba5fc4e6ffcb129c55918c46e0eec69579799249d0"
    end
    on_intel do
      url "https://ziglang.org/builds/zig-x86_64-linux-0.17.0-dev.2320+1e770dbef.tar.xz"
      sha256 "4668738082f1f085ad072eb3306b7bf48d6350c95b99ae20ace24c1f16747490"
    end
  end

  def install
    # The archive unpacks to `zig`, `lib/`, `doc/`, and LICENSE. Keep them
    # together in libexec and expose only the compiler on PATH; Zig finds its
    # std library relative to the resolved binary, so the symlink works.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"zig"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zig version")
  end
end
