# typed: false
# frozen_string_literal: true

# GENERATED by scripts/update-zig-master.py from https://ziglang.org/download/index.json -- do not edit.
# Zig's master channel is a moving target (only the latest nightly is kept
# online), so the `update-zig-master` workflow regenerates this file whenever a
# new build is published. Edit the script or template, never this file.
class ZigMaster < Formula
  desc "Programming language designed for robustness, optimality, and clarity"
  homepage "https://ziglang.org"
  version "0.18.0-dev.35+5e754304d"
  license "MIT"

  on_macos do
    on_arm do
      url "https://ziglang.org/builds/zig-aarch64-macos-0.18.0-dev.35+5e754304d.tar.xz"
      sha256 "6470bf41226db6f675220c1b682c0ed67c4ab1a446533846e242ceda61a94f61"
    end
    on_intel do
      url "https://ziglang.org/builds/zig-x86_64-macos-0.18.0-dev.35+5e754304d.tar.xz"
      sha256 "729282b70e076999ec84ae7016ec549b0c0463ead91e323bae4a31a39a4fd70b"
    end
  end

  on_linux do
    on_arm do
      url "https://ziglang.org/builds/zig-aarch64-linux-0.18.0-dev.35+5e754304d.tar.xz"
      sha256 "05bbe123c442dc85581b47eb06b04f04f0fa0e6af95f5aaea4eb2359be2efac9"
    end
    on_intel do
      url "https://ziglang.org/builds/zig-x86_64-linux-0.18.0-dev.35+5e754304d.tar.xz"
      sha256 "cda25c1d2d8f10152b4c0ab797c41a5627a1395316083958870398fa136d766b"
    end
  end

  def install
    # The archive unpacks to `zig`, `lib/`, `doc/`, and LICENSE. Keep them
    # together in libexec and expose only the compiler on PATH; Zig finds its
    # std library relative to the resolved binary, so the symlink works.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"zig"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zig version")
  end
end
