# typed: false
# frozen_string_literal: true

# GENERATED by scripts/update-zls-master.py -- do not edit.
# ZLS has no standalone "master" channel, so this pins the latest ZLS nightly
# that is runtime-compatible with Zig's current master build, resolved through
# https://releases.zigtools.org/v1/zls/select-version. The update-zls-master
# workflow regenerates this file whenever that pairing changes.
class ZlsMaster < Formula
  desc "Language server for the Zig programming language"
  homepage "https://github.com/zigtools/zls"
  version "0.17.0-dev.44+8da87d4f"
  license "MIT"

  on_macos do
    on_arm do
      url "https://builds.zigtools.org/zls-aarch64-macos-0.17.0-dev.44+8da87d4f.tar.xz"
      sha256 "e14170c554c2306a17402a81c9058915c36f69282504d4dbe04b2ff1d3c380cf"
    end
    on_intel do
      url "https://builds.zigtools.org/zls-x86_64-macos-0.17.0-dev.44+8da87d4f.tar.xz"
      sha256 "477e2cd6440643960c4c372c1d14c35d7093cace526fd08c6c072e091fdb1785"
    end
  end

  on_linux do
    on_arm do
      url "https://builds.zigtools.org/zls-aarch64-linux-0.17.0-dev.44+8da87d4f.tar.xz"
      sha256 "ea9a8b194f7e74409e16b26747a1efd40c094381d22e18af340a7b826d454203"
    end
    on_intel do
      url "https://builds.zigtools.org/zls-x86_64-linux-0.17.0-dev.44+8da87d4f.tar.xz"
      sha256 "9ea223fa88424671555911beba5d689191ae080a4e827ef5c76c8f64e39ff296"
    end
  end

  def install
    # The archive is a bare `zls` binary plus LICENSE/README at the root.
    bin.install "zls"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zls --version")
  end
end
