#!/usr/bin/env python3
"""Regenerate Formula/tileserver-gl.rb from the npm registry.

tileserver-gl is published only to npm (no standalone binaries) and pulls native
modules at install time. Its renderer, @maplibre/maplibre-gl-native, uses
node-pre-gyp with --fallback-to-build=false: it downloads a prebuilt binary keyed
to the *exact* Node ABI and never compiles from source. Only a handful of ABIs
are published per release, so the formula MUST depend on a Node whose ABI
maplibre ships a macOS prebuild for -- Homebrew's current `node` is usually too
new. This script:

  1. reads tileserver-gl's latest release from the npm registry (version, tarball,
     its pinned maplibre-gl-native version, and its `engines.node` range) and
     computes the tarball's sha256,
  2. inspects maplibre-native's GitHub release assets to see which in-range Node
     ABIs have macOS (arm64 + x64) prebuilds, and
  3. regenerates the formula pinned to npm + the chosen `node@<major>`.

If no in-range Node has a macOS prebuild it fails loudly, rather than emit a
formula that cannot install.

Run it locally, or let the `update-tileserver-gl` GitHub Actions workflow run it
on a schedule and commit the result.

Usage:
    python3 scripts/update-tileserver-gl.py [--check]

    --check   Exit 1 (without writing) if the formula is out of date. Useful in
              CI to tell whether a refresh is needed.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import urllib.request

NPM_LATEST_URL = "https://registry.npmjs.org/tileserver-gl/latest"
MAPLIBRE_PKG = "@maplibre/maplibre-gl-native"
MAPLIBRE_RELEASE_URL = "https://api.github.com/repos/maplibre/maplibre-native/releases/tags/node-v{version}"
UA = {"User-Agent": "unships-tap/update-tileserver-gl"}

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FORMULA_PATH = os.path.join(REPO_ROOT, "Formula", "tileserver-gl.rb")

# NODE_MODULE_VERSION (a.k.a. node_abi) per Node major. node-pre-gyp names its
# prebuilt assets `node-v<abi>-<platform>-<arch>-Release.tar.gz`.
NODE_ABI = {18: 108, 20: 115, 22: 127, 24: 137, 26: 147}
# When several in-range majors have a prebuild, prefer this one (LTS; the major
# the formula was first validated against). Falls back to the newest available.
PREFERRED_MAJOR = 22
# macOS slices we need a maplibre prebuild for (the formula is macOS-only).
MACOS_SLICES = ("darwin-arm64", "darwin-x64")

TEMPLATE = """\
# typed: false
# frozen_string_literal: true

# GENERATED by scripts/update-tileserver-gl.py from the npm registry -- do not edit.
# tileserver-gl ships only via npm and pulls native modules at install time. Its
# renderer (@maplibre/maplibre-gl-native) downloads an ABI-specific prebuilt binary
# with no source fallback, so this formula pins a Node whose ABI maplibre actually
# publishes a macOS prebuild for (@@NODE_DEP@@ here). The update-tileserver-gl
# workflow regenerates this file -- re-picking the Node line -- on new releases.
# Edit the script or template, never this file.
class TileserverGl < Formula
  desc "Map tile server for vector and raster tiles with server-side GL rendering"
  homepage "https://github.com/maptiler/tileserver-gl"
  url "@@TARBALL_URL@@"
  sha256 "@@SHA256@@"
  license "BSD-2-Clause"

  depends_on :macos
  depends_on "@@NODE_DEP@@"

  def install
    node = Formula["@@NODE_DEP@@"]
    ENV.prepend_path "PATH", node.opt_bin

    # sharp builds from source when it detects a globally-installed libvips (e.g.
    # from `brew install vips`), which would need a toolchain this formula does
    # not pull in. Force its self-contained prebuilt binaries instead.
    ENV["SHARP_IGNORE_GLOBAL_LIBVIPS"] = "1"

    # Install runtime deps in-tree. maplibre-gl-native and canvas resolve prebuilt,
    # self-contained binaries (their dylibs are bundled beside the .node files), so
    # no Homebrew cairo/pango/vips dependencies are needed. Don't build from source
    # -- maplibre publishes no source fallback for these ABIs anyway.
    system node.opt_bin/"npm", "install", "--omit=dev", "--no-audit", "--no-fund"

    libexec.install Dir["*"]

    # main.js' shebang is `#!/usr/bin/env node`; if another Node (e.g. Homebrew's
    # current `node`) comes first on PATH, the prebuilt native ABI mismatches and
    # crashes. Pin the interpreter to the Node this was built against.
    (bin/"tileserver-gl").write <<~SH
      #!/bin/bash
      exec "#{node.opt_bin}/node" "#{libexec}/src/main.js" "$@"
    SH
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tileserver-gl --version")
  end
end
"""


def fetch_json(url: str) -> dict:
    headers = dict(UA)
    token = os.environ.get("GITHUB_TOKEN")
    if token and "api.github.com" in url:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.load(resp)


def sha256_of(url: str) -> str:
    req = urllib.request.Request(url, headers=UA)
    digest = hashlib.sha256()
    with urllib.request.urlopen(req, timeout=120) as resp:
        for chunk in iter(lambda: resp.read(1 << 16), b""):
            digest.update(chunk)
    return digest.hexdigest()


def parse_engine_majors(engines: dict) -> list[int]:
    spec = (engines or {}).get("node", "")
    majors = sorted({int(m) for m in re.findall(r"\d+", spec)})
    if not majors:
        raise SystemExit(f"could not parse engines.node from {engines!r}")
    return majors


def maplibre_version(deps: dict) -> str:
    raw = (deps or {}).get(MAPLIBRE_PKG)
    if not raw:
        raise SystemExit(f"tileserver-gl no longer depends on {MAPLIBRE_PKG}; "
                         "the Node-pinning logic needs revisiting")
    match = re.search(r"\d+\.\d+\.\d+", raw)
    if not match:
        raise SystemExit(f"unexpected {MAPLIBRE_PKG} version spec: {raw!r}")
    return match.group(0)


def pick_node_major(mlb_version: str, engine_majors: list[int]) -> int:
    release = fetch_json(MAPLIBRE_RELEASE_URL.format(version=mlb_version))
    asset_names = {asset["name"] for asset in release.get("assets", [])}
    if not asset_names:
        raise SystemExit(f"no assets on maplibre-native release node-v{mlb_version}")

    available = []
    for major in engine_majors:
        abi = NODE_ABI.get(major)
        if abi is None:
            continue  # unknown ABI for this major; can't confirm a prebuild exists
        if all(f"node-v{abi}-{slice_}-Release.tar.gz" in asset_names for slice_ in MACOS_SLICES):
            available.append(major)

    if not available:
        raise SystemExit(
            f"maplibre-native {mlb_version} publishes no macOS prebuild for any Node "
            f"in tileserver-gl's engines range {engine_majors} (known ABIs {NODE_ABI}); "
            "refusing to emit an uninstallable formula")

    return PREFERRED_MAJOR if PREFERRED_MAJOR in available else max(available)


# Homebrew scans the version straight from the npm tarball URL, so the formula
# intentionally omits a `version` line (an explicit one trips `brew audit
# --strict`). We still surface the version in logs/commit messages.
def render(tarball_url: str, sha256: str, node_major: int) -> str:
    out = (TEMPLATE
           .replace("@@TARBALL_URL@@", tarball_url)
           .replace("@@SHA256@@", sha256)
           .replace("@@NODE_DEP@@", f"node@{node_major}"))
    if "@@" in out:
        raise SystemExit(f"unfilled template token(s) remain:\n{out}")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the formula is out of date; do not write")
    args = parser.parse_args()

    pkg = fetch_json(NPM_LATEST_URL)
    version = pkg["version"]
    tarball_url = pkg["dist"]["tarball"]
    engine_majors = parse_engine_majors(pkg.get("engines", {}))
    mlb_version = maplibre_version(pkg.get("dependencies", {}))
    node_major = pick_node_major(mlb_version, engine_majors)
    sha256 = sha256_of(tarball_url)

    rendered = render(tarball_url, sha256, node_major)

    current = None
    if os.path.exists(FORMULA_PATH):
        with open(FORMULA_PATH, encoding="utf-8") as fh:
            current = fh.read()

    if current == rendered:
        print(f"tileserver-gl is up to date at {version} "
              f"(node@{node_major}, maplibre-gl-native {mlb_version})")
        return 0

    if args.check:
        print(f"tileserver-gl is OUT OF DATE (would update to {version}, node@{node_major})")
        return 1

    os.makedirs(os.path.dirname(FORMULA_PATH), exist_ok=True)
    with open(FORMULA_PATH, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"wrote {os.path.relpath(FORMULA_PATH, REPO_ROOT)} -> {version} "
          f"(node@{node_major}, maplibre-gl-native {mlb_version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
