#!/usr/bin/env python3
"""Regenerate Formula/rassumfrassum.rb from GitHub releases.

rassumfrassum is published to PyPI but tagged on GitHub. This script pins the
formula to the latest GitHub release tarball and its sha256. The
update-rassumfrassum workflow reruns it on a schedule and commits when a new
release lands.

Usage:
    python3 scripts/update-rassumfrassum.py [--check]

    --check   Exit 1 (without writing) if the formula is out of date.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import urllib.request

GITHUB_RELEASES_URL = "https://api.github.com/repos/joaotavora/rassumfrassum/releases/latest"
UA = {"User-Agent": "unships-tap/update-rassumfrassum"}

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FORMULA_PATH = os.path.join(REPO_ROOT, "Formula", "rassumfrassum.rb")

TEMPLATE = """\
# typed: false
# frozen_string_literal: true

# GENERATED by scripts/update-rassumfrassum.py from GitHub releases -- do not edit.
# The update-rassumfrassum workflow regenerates this file on new releases.
# Edit the script or template, never this file.
class Rassumfrassum < Formula
  include Language::Python::Virtualenv

  desc "LSP/JSONRPC multiplexer connecting one LSP client to multiple servers"
  homepage "https://github.com/joaotavora/rassumfrassum"
  url "@@URL@@"
  sha256 "@@SHA256@@"
  license "GPL-3.0-or-later"

  depends_on "python@3.13"

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rass --version")
  end
end
"""


def fetch_json(url: str) -> dict:
    headers = dict(UA)
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.load(resp)


def sha256_of(url: str) -> str:
    req = urllib.request.Request(url, headers=UA)
    digest = hashlib.sha256()
    with urllib.request.urlopen(req, timeout=120) as resp:
        for chunk in iter(lambda: resp.read(1 << 16), b""):
            digest.update(chunk)
    return digest.hexdigest()


def release_version(tag: str) -> str:
    match = re.fullmatch(r"v?(\d+\.\d+\.\d+.*)", tag)
    if not match:
        raise SystemExit(f"unexpected release tag {tag!r}; expected vX.Y.Z")
    return match.group(1)


def tarball_url(tag: str) -> str:
    return f"https://github.com/joaotavora/rassumfrassum/archive/refs/tags/{tag}.tar.gz"


def render(url: str, sha256: str) -> str:
    out = (TEMPLATE
           .replace("@@URL@@", url)
           .replace("@@SHA256@@", sha256))
    if "@@" in out:
        raise SystemExit(f"unfilled template token(s) remain:\n{out}")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the formula is out of date; do not write")
    args = parser.parse_args()

    release = fetch_json(GITHUB_RELEASES_URL)
    tag = release.get("tag_name")
    if not tag:
        raise SystemExit(f"latest release has no tag_name: {release!r}")

    version = release_version(tag)
    url = tarball_url(tag)
    sha256 = sha256_of(url)
    rendered = render(url, sha256)

    current = None
    if os.path.exists(FORMULA_PATH):
        with open(FORMULA_PATH, encoding="utf-8") as fh:
            current = fh.read()

    if current == rendered:
        print(f"rassumfrassum is up to date at {version}")
        return 0

    if args.check:
        print(f"rassumfrassum is OUT OF DATE (would update to {version})")
        return 1

    os.makedirs(os.path.dirname(FORMULA_PATH), exist_ok=True)
    with open(FORMULA_PATH, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"wrote {os.path.relpath(FORMULA_PATH, REPO_ROOT)} -> {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
