#!/usr/bin/env python3
"""Regenerate Formula/zls-master.rb: the latest ZLS nightly that matches Zig master.

Unlike Zig, ZLS has no standalone "master" download index. Instead, ZLS exposes
a version-matching API that, given a Zig version, returns the newest ZLS build
that is runtime-compatible with it:

    https://releases.zigtools.org/v1/zls/select-version

So this script reads Zig's current master version from ziglang.org, asks the API
for the ZLS nightly paired with it, and pins that into the formula. Like Zig's
nightly, those URLs go stale as new builds land, so the `update-zls-master`
GitHub Actions workflow reruns this on a schedule.

Usage:
    python3 scripts/update-zls-master.py [--check]

    --check   Exit 1 (without writing) if the formula is out of date.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

ZIG_INDEX_URL = "https://ziglang.org/download/index.json"
ZLS_SELECT_URL = "https://releases.zigtools.org/v1/zls/select-version"
UA = {"User-Agent": "unships-tap/update-zls-master"}

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FORMULA_PATH = os.path.join(REPO_ROOT, "Formula", "zls-master.rb")

# Homebrew (os, arch) slot -> ZLS platform key.
PLATFORMS = {
    "MACOS_ARM": "aarch64-macos",
    "MACOS_INTEL": "x86_64-macos",
    "LINUX_ARM": "aarch64-linux",
    "LINUX_INTEL": "x86_64-linux",
}

TEMPLATE = """\
# typed: false
# frozen_string_literal: true

# GENERATED by scripts/update-zls-master.py -- do not edit.
# ZLS has no standalone "master" channel, so this pins the latest ZLS nightly
# that is runtime-compatible with Zig's current master build, resolved through
# https://releases.zigtools.org/v1/zls/select-version. The update-zls-master
# workflow regenerates this file whenever that pairing changes.
class ZlsMaster < Formula
  desc "Language server for the Zig programming language"
  homepage "https://github.com/zigtools/zls"
  version "@@VERSION@@"
  license "MIT"

  on_macos do
    on_arm do
      url "@@MACOS_ARM_URL@@"
      sha256 "@@MACOS_ARM_SHA@@"
    end
    on_intel do
      url "@@MACOS_INTEL_URL@@"
      sha256 "@@MACOS_INTEL_SHA@@"
    end
  end

  on_linux do
    on_arm do
      url "@@LINUX_ARM_URL@@"
      sha256 "@@LINUX_ARM_SHA@@"
    end
    on_intel do
      url "@@LINUX_INTEL_URL@@"
      sha256 "@@LINUX_INTEL_SHA@@"
    end
  end

  def install
    # The archive is a bare `zls` binary plus LICENSE/README at the root.
    bin.install "zls"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zls --version")
  end
end
"""


def fetch_zig_master_version() -> str:
    req = urllib.request.Request(ZIG_INDEX_URL, headers=UA)
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.load(resp)["master"]["version"]


def fetch_zls_build(zig_version: str) -> dict:
    query = urllib.parse.urlencode({"zig_version": zig_version, "compatibility": "only-runtime"})
    req = urllib.request.Request(f"{ZLS_SELECT_URL}?{query}", headers=UA)
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.load(resp)
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", "replace")
        raise SystemExit(f"select-version HTTP {exc.code} for zig {zig_version}: {body}")
    # The API returns {"code": N, "message": "..."} when no compatible build exists.
    if "version" not in data:
        raise SystemExit(f"no compatible ZLS build for zig {zig_version}: {data}")
    return data


def render(build: dict) -> str:
    out = TEMPLATE.replace("@@VERSION@@", build["version"])
    for token, plat_key in PLATFORMS.items():
        entry = build[plat_key]  # KeyError -> fail loudly rather than emit a broken formula
        out = out.replace(f"@@{token}_URL@@", entry["tarball"])
        out = out.replace(f"@@{token}_SHA@@", entry["shasum"])
    if "@@" in out:
        raise SystemExit(f"unfilled template token(s) remain:\n{out}")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the formula is out of date; do not write")
    args = parser.parse_args()

    zig_version = fetch_zig_master_version()
    build = fetch_zls_build(zig_version)
    rendered = render(build)

    current = None
    if os.path.exists(FORMULA_PATH):
        with open(FORMULA_PATH, encoding="utf-8") as fh:
            current = fh.read()

    if current == rendered:
        print(f"zls-master is up to date at {build['version']} (zig master {zig_version})")
        return 0

    if args.check:
        print(f"zls-master is OUT OF DATE (would update to {build['version']})")
        return 1

    os.makedirs(os.path.dirname(FORMULA_PATH), exist_ok=True)
    with open(FORMULA_PATH, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"wrote {os.path.relpath(FORMULA_PATH, REPO_ROOT)} -> {build['version']} "
          f"(matched to zig master {zig_version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
