#!/usr/bin/env python3
"""Regenerate Formula/zig-master.rb from Zig's master (nightly) channel.

Zig's master channel is a moving target: ziglang.org keeps only the *latest*
nightly build and deletes older ones, so any URL/checksum pinned in the formula
goes stale (404s) within a day or two. This script re-pins the formula to the
current master build listed in https://ziglang.org/download/index.json.

Run it locally, or let the `update-zig-master` GitHub Actions workflow run it on
a schedule and commit the result.

Usage:
    python3 scripts/update-zig-master.py [--check]

    --check   Exit 1 (without writing) if the formula is out of date. Useful in
              CI to tell whether a refresh is needed.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request

INDEX_URL = "https://ziglang.org/download/index.json"
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FORMULA_PATH = os.path.join(REPO_ROOT, "Formula", "zig-master.rb")

# Homebrew (os, arch) slot -> Zig index.json platform key.
PLATFORMS = {
    "MACOS_ARM": "aarch64-macos",
    "MACOS_INTEL": "x86_64-macos",
    "LINUX_ARM": "aarch64-linux",
    "LINUX_INTEL": "x86_64-linux",
}

TEMPLATE = """\
# typed: false
# frozen_string_literal: true

# GENERATED by scripts/update-zig-master.py from @@INDEX_URL@@ -- do not edit.
# Zig's master channel is a moving target (only the latest nightly is kept
# online), so the `update-zig-master` workflow regenerates this file whenever a
# new build is published. Edit the script or template, never this file.
class ZigMaster < Formula
  desc "Programming language designed for robustness, optimality, and clarity"
  homepage "https://ziglang.org"
  version "@@VERSION@@"
  license "MIT"

  on_macos do
    on_arm do
      url "@@MACOS_ARM_URL@@"
      sha256 "@@MACOS_ARM_SHA@@"
    end
    on_intel do
      url "@@MACOS_INTEL_URL@@"
      sha256 "@@MACOS_INTEL_SHA@@"
    end
  end

  on_linux do
    on_arm do
      url "@@LINUX_ARM_URL@@"
      sha256 "@@LINUX_ARM_SHA@@"
    end
    on_intel do
      url "@@LINUX_INTEL_URL@@"
      sha256 "@@LINUX_INTEL_SHA@@"
    end
  end

  def install
    # The archive unpacks to `zig`, `lib/`, `doc/`, and LICENSE. Keep them
    # together in libexec and expose only the compiler on PATH; Zig finds its
    # std library relative to the resolved binary, so the symlink works.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"zig"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zig version")
  end
end
"""


def fetch_master() -> dict:
    req = urllib.request.Request(INDEX_URL, headers={"User-Agent": "unships-tap/update-zig-master"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        index = json.load(resp)
    master = index["master"]
    if "version" not in master:
        raise SystemExit("index.json 'master' entry has no version field")
    return master


def render(master: dict) -> str:
    out = TEMPLATE.replace("@@INDEX_URL@@", INDEX_URL)
    out = out.replace("@@VERSION@@", master["version"])
    for token, plat_key in PLATFORMS.items():
        entry = master[plat_key]  # KeyError -> fail loudly rather than emit a broken formula
        out = out.replace(f"@@{token}_URL@@", entry["tarball"])
        out = out.replace(f"@@{token}_SHA@@", entry["shasum"])
    if "@@" in out:
        raise SystemExit(f"unfilled template token(s) remain:\n{out}")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the formula is out of date; do not write")
    args = parser.parse_args()

    master = fetch_master()
    rendered = render(master)

    current = None
    if os.path.exists(FORMULA_PATH):
        with open(FORMULA_PATH, encoding="utf-8") as fh:
            current = fh.read()

    if current == rendered:
        print(f"zig-master is up to date at {master['version']}")
        return 0

    if args.check:
        print(f"zig-master is OUT OF DATE (would update to {master['version']})")
        return 1

    os.makedirs(os.path.dirname(FORMULA_PATH), exist_ok=True)
    with open(FORMULA_PATH, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"wrote {os.path.relpath(FORMULA_PATH, REPO_ROOT)} -> {master['version']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
